name: english_learner_flutter_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  is_first_run: ^1.0.0
  flutter_svg: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/

  fonts:
    - family: RedHatDisplay
      fonts:
        - asset: fonts/RedHatDisplay-Italic-VariableFont_wght.ttf
        - asset: fonts/RedHatDisplay-VariableFont_wght.ttf

    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans-Regular.ttf
        - asset: fonts/OpenSans-Medium.ttf
        - asset: fonts/OpenSans-Bold.ttf
        - asset: fonts/OpenSans-SemiBold.ttf



